name: Test Publish Vocabulary Workflow

on:
    push:
        branches:
            - main
    pull_request:


jobs:
    test-workflow-csv:
        uses: ./.github/workflows/csv2skos.yml
        with:
            ref: ${{ github.ref }}
            namespace: http://www.example.com/
            namespace_label: example
            mappings_file: rules/mappings.yarrr.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

    test-workflow-yml:
        uses: ./.github/workflows/yml2skos.yml
        with:
            ref: ${{ github.ref }}
            namespace: http://www.example.com/
            voc_uri: http://www.example.com/person-vocabulary
            entity_name: Person
            linkml_schema: schema/people.linkml.yml
            data: data/people.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}

